# Generated by Django 5.2.5 on 2025-08-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('ingredients', models.TextField(help_text='Enter ingredients (comma separated)')),
                ('cooking_time', models.IntegerField(help_text='Enter cooking time (in minutes)')),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('likes', models.IntegerField(default=0, help_text='Number of likes (auto-calculated)')),
                ('comments', models.TextField(blank=True, help_text='User comments (future feature)')),
                ('references', models.URLField(blank=True)),
            ],
        ),
    ]
