# Generated by Django 5.2.5 on 2025-08-17 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(help_text='Enter cooking time (in minutes)', validators=[django.core.validators.MinValueValidator(1, message='Cooking time must be at least 1 minute'), django.core.validators.MaxValueValidator(1440, message='Cooking time cannot exceed 24 hours (1440 minutes)')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, help_text='Difficulty level (auto-calculated)', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Enter the recipe name', max_length=120),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='references',
            field=models.URLField(blank=True, help_text='Optional reference URL'),
        ),
    ]
