# Generated by Django 5.2.5 on 2025-08-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_cooking_time_alter_recipe_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='comments',
            field=models.TextField(blank=True, editable=False, help_text='User comments (future feature, readonly)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.IntegerField(default=0, editable=False, help_text='Number of likes (auto-calculated, readonly)'),
        ),
    ]
