# Generated by Django 5.2.5 on 2025-08-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_comments_alter_recipe_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(blank=True, editable=False, help_text='Difficulty level (auto-calculated, readonly)', max_length=20),
        ),
    ]
