# Generated by Django 5.2.5 on 2025-09-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_description',
            field=models.TextField(blank=True, help_text='Enter a short description of the recipe', max_length=300),
        ),
    ]
